package ctecs

import (
	"github.com/ctyun-it/ctyun-sdk-go/ctyun-sdk-core"
)

// Apis api的接口
type Apis struct {
	RegionListApi                          *RegionListApi
	KeypairAttachApi                       *KeypairAttachApi
	KeypairDetachApi                       *KeypairDetachApi
	KeypairCreateApi                       *KeypairCreateApi
	KeypairDeleteApi                       *KeypairDeleteApi
	KeypairDetailApi                       *KeypairDetailApi
	KeypairImportApi                       *KeypairImportApi
	EcsDescribeInstancesApi                *EcsDescribeInstancesApi
	EcsFlavorListApi                       *EcsFlavorListApi
	EcsCreateInstanceApi                   *EcsCreateInstanceApi
	EcsJoinSecurityGroupApi                *EcsJoinSecurityGroupApi
	EcsLeaveSecurityGroupApi               *EcsLeaveSecurityGroupApi
	EcsVolumeListApi                       *EcsVolumeListApi
	EcsInstanceDetailsApi                  *EcsInstanceDetailsApi
	EcsUnsubscribeInstanceApi              *EcsUnsubscribeInstanceApi
	EcsUpdateFlavorSpecApi                 *EcsUpdateFlavorSpecApi
	EcsQueryAsyncResultApi                 *EcsQueryAsyncResultApi
	EcsStartInstanceApi                    *EcsStartInstanceApi
	EcsStopInstanceApi                     *EcsStopInstanceApi
	EcsInstanceStatusListApi               *EcsInstanceStatusListApi
	EcsResetPasswordApi                    *EcsResetPasswordApi
	EcsChangeToCycleApi                    *EcsChangeToCycleApi
	EcsTagOnDemandApi                      *EcsTagOnDemandApi
	EcsTerminateCycleApi                   *EcsTerminateCycleApi
	EcsBatchUpdateInstancesApi             *EcsBatchUpdateInstancesApi
	JobShowApi                             *JobShowApi
	EcsOrderQueryUuidApi                   *EcsOrderQueryUuidApi
	SecurityGroupRuleEgressCreateApi       *SecurityGroupRuleEgressCreateApi
	SecurityGroupRuleIngressCreateApi      *SecurityGroupRuleIngressCreateApi
	EcsRebootInstanceApi                   *EcsRebootInstanceApi
	EcsRebuildInstanceApi                  *EcsRebuildInstanceApi
	EcsBatchRebootInstancesApi             *EcsBatchRebootInstancesApi
	EcsBatchRebuildInstancesApi            *EcsBatchRebuildInstancesApi
	EcsBatchUnsubscribeInstancesApi        *EcsBatchUnsubscribeInstancesApi
	EcsVmDiskLatestMetricDataApi           *EcsVmDiskLatestMetricDataApi
	EcsVmCpuLatestMetricDataApi            *EcsVmCpuLatestMetricDataApi
	EcsVmNetworkHistoryMetricDataApi       *EcsVmNetworkHistoryMetricDataApi
	EcsVmMemHistoryMetricDataApi           *EcsVmMemHistoryMetricDataApi
	EcsVmDiskHistoryMetricDataApi          *EcsVmDiskHistoryMetricDataApi
	EcsVmCpuHistoryMetricDataApi           *EcsVmCpuHistoryMetricDataApi
	EcsBackupCreateApi                     *EcsBackupCreateApi
	EcsBackupUpdateApi                     *EcsBackupUpdateApi
	EcsBackupBatchUpdateApi                *EcsBackupBatchUpdateApi
	EcsBackupUsageApi                      *EcsBackupUsageApi
	EcsBackupStatisticsApi                 *EcsBackupStatisticsApi
	EcsBackupInstanceResourceApi           *EcsBackupInstanceResourceApi
	EcsBackupListApi                       *EcsBackupListApi
	EcsBackupDetailsApi                    *EcsBackupDetailsApi
	EcsBackupInstanceDetailsApi            *EcsBackupInstanceDetailsApi
	EcsBackupStatusApi                     *EcsBackupStatusApi
	EcsBackupRestoreApi                    *EcsBackupRestoreApi
	EcsBackupDeleteApi                     *EcsBackupDeleteApi
	EcsAgentBatchActionApi                 *EcsAgentBatchActionApi
	EcsPortsCreateApi                      *EcsPortsCreateApi
	EcsPortsDeleteApi                      *EcsPortsDeleteApi
	EcsPortsUpdateApi                      *EcsPortsUpdateApi
	EcsPortsListApi                        *EcsPortsListApi
	EcsPortsShowApi                        *EcsPortsShowApi
	EcsPortsAttachApi                      *EcsPortsAttachApi
	EcsPortsDetachApi                      *EcsPortsDetachApi
	EcsPortsAssignIpv6Api                  *EcsPortsAssignIpv6Api
	EcsPortsUnassignIpv6Api                *EcsPortsUnassignIpv6Api
	EcsPortsAssignSecondaryPrivateIpsApi   *EcsPortsAssignSecondaryPrivateIpsApi
	EcsPortsUnassignSecondaryPrivateIpsApi *EcsPortsUnassignSecondaryPrivateIpsApi
	EcsEipCreateApi                        *EcsEipCreateApi
	EcsEipDeleteApi                        *EcsEipDeleteApi
	EcsShareInterfaceAttachApi             *EcsShareInterfaceAttachApi
	EcsBackupCreateInstanceApi             *EcsBackupCreateInstanceApi
	EcsBatchStopInstancesApi               *EcsBatchStopInstancesApi
	EcsUpdateNetworkSpecApi                *EcsUpdateNetworkSpecApi
	EcsUpdateInstanceSpecApi               *EcsUpdateInstanceSpecApi
	EcsGpuDriverListApi                    *EcsGpuDriverListApi
	EcsFlavorListByFamiliesApi             *EcsFlavorListByFamiliesApi
	EcsBatchCreateInstancesApi             *EcsBatchCreateInstancesApi
	EcsListInstancesApi                    *EcsListInstancesApi
	EcsAvailabilityZonesDetailsApi         *EcsAvailabilityZonesDetailsApi
	EcsFlavorFamiliesListApi               *EcsFlavorFamiliesListApi
	EcsUpdateInstanceApi                   *EcsUpdateInstanceApi
	EcsVncDetailsApi                       *EcsVncDetailsApi
	EcsVolumeStatisticsApi                 *EcsVolumeStatisticsApi
	EcsBatchResetPasswordApi               *EcsBatchResetPasswordApi
	EcsBackupPolicyListApi                 *EcsBackupPolicyListApi
	EcsBackupPolicyListInstancesApi        *EcsBackupPolicyListInstancesApi
	EcsBackupPolicyBindInstancesApi        *EcsBackupPolicyBindInstancesApi
	EcsBackupPolicyUnbindInstancesApi      *EcsBackupPolicyUnbindInstancesApi
	EcsBackupPolicyBindRepoApi             *EcsBackupPolicyBindRepoApi
	EcsBackupPolicyUnbindRepoApi           *EcsBackupPolicyUnbindRepoApi
	EcsCreateSnapshotApi                   *EcsCreateSnapshotApi
	EcsRestoreSnapshotApi                  *EcsRestoreSnapshotApi
	EcsUpdateSnapshotApi                   *EcsUpdateSnapshotApi
	EcsSnapshotBatchUpdateApi              *EcsSnapshotBatchUpdateApi
	EcsSnapshotListApi                     *EcsSnapshotListApi
	EcsSnapshotDetailsApi                  *EcsSnapshotDetailsApi
	EcsSnapshotStatisticsApi               *EcsSnapshotStatisticsApi
	EcsSnapshotStatusApi                   *EcsSnapshotStatusApi
	EcsSnapshotDeleteApi                   *EcsSnapshotDeleteApi
}

// NewApis 构建
func NewApis(client *ctyunsdk.CtyunClient) *Apis {
	client.RegisterEndpoint(ctyunsdk.EnvironmentDev, EndpointCtecsTest)
	client.RegisterEndpoint(ctyunsdk.EnvironmentTest, EndpointCtecsTest)
	client.RegisterEndpoint(ctyunsdk.EnvironmentProd, EndpointCtecsProd)
	return &Apis{
		RegionListApi:                          NewRegionListApi(client),
		KeypairAttachApi:                       NewKeypairAttachApi(client),
		KeypairDetachApi:                       NewKeypairDetachApi(client),
		KeypairCreateApi:                       NewKeypairCreateApi(client),
		KeypairDeleteApi:                       NewKeypairDeleteApi(client),
		KeypairDetailApi:                       NewKeypairDetailApi(client),
		KeypairImportApi:                       NewKeypairImportApi(client),
		EcsDescribeInstancesApi:                NewEcsDescribeInstancesApi(client),
		EcsFlavorListApi:                       NewEcsFlavorListApi(client),
		EcsCreateInstanceApi:                   NewEcsCreateInstanceApi(client),
		EcsJoinSecurityGroupApi:                NewEcsJoinSecurityGroupApi(client),
		EcsLeaveSecurityGroupApi:               NewEcsLeaveSecurityGroupApi(client),
		EcsVolumeListApi:                       NewEcsVolumeListApi(client),
		EcsInstanceDetailsApi:                  NewEcsInstanceDetailsApi(client),
		EcsUnsubscribeInstanceApi:              NewEcsUnsubscribeInstanceApi(client),
		EcsUpdateFlavorSpecApi:                 NewEcsUpdateFlavorSpecApi(client),
		EcsQueryAsyncResultApi:                 NewEcsQueryAsyncResultApi(client),
		EcsStartInstanceApi:                    NewEcsStartInstanceApi(client),
		EcsStopInstanceApi:                     NewEcsStopInstanceApi(client),
		EcsInstanceStatusListApi:               NewEcsInstanceStatusListApi(client),
		EcsResetPasswordApi:                    NewEcsResetPasswordApi(client),
		EcsChangeToCycleApi:                    NewEcsChangeToCycleApi(client),
		EcsTagOnDemandApi:                      NewEcsTagOnDemandApi(client),
		EcsTerminateCycleApi:                   NewEcsTerminateCycleApi(client),
		EcsBatchUpdateInstancesApi:             NewEcsBatchUpdateInstancesApi(client),
		JobShowApi:                             NewJobShowApi(client),
		EcsOrderQueryUuidApi:                   NewEcsOrderQueryUuid(client),
		SecurityGroupRuleEgressCreateApi:       NewSecurityGroupRuleEgressCreateApi(client),
		SecurityGroupRuleIngressCreateApi:      NewSecurityGroupRuleIngressCreateApi(client),
		EcsRebootInstanceApi:                   NewEcsRebootInstanceApi(client),
		EcsRebuildInstanceApi:                  NewEcsRebuildInstanceApi(client),
		EcsBatchRebootInstancesApi:             NewEcsBatchRebootInstanceApi(client),
		EcsBatchRebuildInstancesApi:            NewEcsBatchRebuildInstancesApi(client),
		EcsBatchUnsubscribeInstancesApi:        NewEcsBatchUnsubscribeInstanceApi(client),
		EcsVmDiskLatestMetricDataApi:           NewEcsVmDiskLatestMetricDataApi(client),
		EcsVmCpuLatestMetricDataApi:            NewEcsVmCpuLatestMetricDataApi(client),
		EcsVmNetworkHistoryMetricDataApi:       NewEcsVmNetworkHistoryMetricDataApi(client),
		EcsVmMemHistoryMetricDataApi:           NewEcsVmMemHistoryMetricDataApi(client),
		EcsVmDiskHistoryMetricDataApi:          NewEcsVmDiskHistoryMetricDataApi(client),
		EcsVmCpuHistoryMetricDataApi:           NewEcsVmCpuHistoryMetricDataApi(client),
		EcsBackupCreateApi:                     NewEcsBackupCreateApi(client),
		EcsBackupUpdateApi:                     NewEcsBackupUpdateApi(client),
		EcsBackupBatchUpdateApi:                NewEcsBackupBatchUpdateApi(client),
		EcsBackupUsageApi:                      NewEcsBackupUsageApi(client),
		EcsBackupStatisticsApi:                 NewEcsBackupStatisticsApi(client),
		EcsBackupInstanceResourceApi:           NewEcsBackupInstanceResourceApi(client),
		EcsBackupListApi:                       NewEcsBackupListApi(client),
		EcsBackupDetailsApi:                    NewEcsBackupDetailsApi(client),
		EcsBackupInstanceDetailsApi:            NewEcsBackupInstanceDetailsApi(client),
		EcsBackupStatusApi:                     NewEcsBackupStatusApi(client),
		EcsBackupRestoreApi:                    NewEcsBackupRestoreApi(client),
		EcsBackupDeleteApi:                     NewEcsBackupDeleteApi(client),
		EcsAgentBatchActionApi:                 NewEcsAgentBatchActionApi(client),
		EcsPortsCreateApi:                      NewEcsPortsCreateApi(client),
		EcsPortsDeleteApi:                      NewEcsPortsDeleteApi(client),
		EcsPortsUpdateApi:                      NewEcsPortsUpdateApi(client),
		EcsPortsListApi:                        NewEcsPortsListApi(client),
		EcsPortsShowApi:                        NewEcsPortsShowApi(client),
		EcsPortsAttachApi:                      NewEcsPortsAttachApi(client),
		EcsPortsDetachApi:                      NewEcsPortsDetachApi(client),
		EcsPortsAssignIpv6Api:                  NewEcsPortsAssignIpv6Api(client),
		EcsPortsUnassignIpv6Api:                NewEcsPortsUnassignIpv6Api(client),
		EcsPortsAssignSecondaryPrivateIpsApi:   NewEcsPortsAssignSecondaryPrivateIpsApi(client),
		EcsPortsUnassignSecondaryPrivateIpsApi: NewEcsPortsUnassignSecondaryPrivateIpsApi(client),
		EcsEipCreateApi:                        NewEcsEipCreateApi(client),
		EcsEipDeleteApi:                        NewEcsEipDeleteApi(client),
		EcsShareInterfaceAttachApi:             NewEcsShareInterfaceAttachApi(client),
		EcsBackupCreateInstanceApi:             NewEcsBackupCreateInstanceApi(client),
		EcsBatchStopInstancesApi:               NewEcsBatchStopInstancesApi(client),
		EcsUpdateNetworkSpecApi:                NewEcsUpdateNetworkSpecApi(client),
		EcsUpdateInstanceSpecApi:               NewEcsUpdateInstanceSpecApi(client),
		EcsGpuDriverListApi:                    NewEcsGpuDriverListApi(client),
		EcsFlavorListByFamiliesApi:             NewEcsFlavorListByFamiliesApi(client),
		EcsBatchCreateInstancesApi:             NewEcsBatchCreateInstancesApi(client),
		EcsListInstancesApi:                    NewEcsListInstancesApi(client),
		EcsAvailabilityZonesDetailsApi:         NewEcsAvailabilityZonesDetails(client),
		EcsFlavorFamiliesListApi:               NewEcsFlavorFamiliesList(client),
		EcsUpdateInstanceApi:                   NewEcsUpdateInstanceApi(client),
		EcsVncDetailsApi:                       NewEcsVncDetailsApi(client),
		EcsVolumeStatisticsApi:                 NewEcsVolumeStatisticsApi(client),
		EcsBatchResetPasswordApi:               NewEcsBatchResetPasswordApi(client),
		EcsBackupPolicyListApi:                 NewEcsBackupPolicyListApi(client),
		EcsBackupPolicyListInstancesApi:        NewEcsBackupPolicyListInstancesApi(client),
		EcsBackupPolicyBindInstancesApi:        NewEcsBackupPolicyBindInstancesApi(client),
		EcsBackupPolicyUnbindInstancesApi:      NewEcsBackupPolicyUnbindInstancesApi(client),
		EcsBackupPolicyBindRepoApi:             NewEcsBackupPolicyBindRepoApi(client),
		EcsBackupPolicyUnbindRepoApi:           NewEcsBackupPolicyUnbindRepoApi(client),
		EcsCreateSnapshotApi:                   NewEcsCreateSnapshotApi(client),
		EcsRestoreSnapshotApi:                  NewEcsRestoreSnapshotApi(client),
		EcsUpdateSnapshotApi:                   NewEcsUpdateSnapshotApi(client),
		EcsSnapshotBatchUpdateApi:              NewEcsSnapshotBatchUpdateApi(client),
		EcsSnapshotListApi:                     NewEcsSnapshotListApi(client),
		EcsSnapshotDetailsApi:                  NewEcsSnapshotDetailsApi(client),
		EcsSnapshotStatisticsApi:               NewEcsSnapshotStatisticsApi(client),
		EcsSnapshotStatusApi:                   NewEcsSnapshotStatusApi(client),
		EcsSnapshotDeleteApi:                   NewEcsSnapshotDeleteApi(client),
	}
}
